#!/usr/bin/env python3

import numpy as np
from ase.io import read

from .neighborTools import neighbors
from .exact_potential import formal_charges
from .constant_calcmad import coef_pot

def get_finite_potential(poscarfile, frac_sites, rCut = 35.0, atom = 0, cAtom = None, cAtomIndex = None):
    """
    Calculate the electrostatic potential for a given crystal (poscarFile) at given 
    sites (frac_sites). The potential is generated by atoms within a spherical cutoff.  
    """
    # crystal information
    mol = read(poscarfile)
    cell = mol.get_cell()
    fracs = mol.get_scaled_positions()
    symbols = mol.get_chemical_symbols()
    # neighbor information
    nbs = neighbors(poscarfile, atom, rCut, cAtom, cAtomIndex)
    indices, offsets = nbs.get_neighbors()
    # calculate electrostatic potential now
    potential = np.zeros(len(frac_sites))
    for i, site in enumerate(frac_sites):
        for j, offset in zip(indices, offsets):
            displacement = np.matmul(fracs[j] - site + offset, cell)
            d = np.linalg.norm(displacement) # d unit: A
            potential[i] += formal_charges[symbols[j]] / d
    potential *= coef_pot   # convert to unit of V
    return potential