import numpy as np

from ase.io import read
from .genSites import gen_random_sites
from .exact_potential import get_exact_potential
from .finite_potential import get_finite_potential
from .neighborTools import neighbors
from .constant_calcmad import coef_pot

class PotentialFitOnlyCharges(object):
    """
    Perform potential fit for the difference between exact and finite potential by adjusting
    the charge values at rCut <= r < rSurface. The problem is reduced to a linear least-squares
    problem and we used SVD to solve it.
    """
    
    def __init__(self, poscarfile, atom = 0, rCut = 10, rSurface = 12.0, num_sites = 500, cAtom = None, cAtomIndex = None) -> None:
        super().__init__()
        
        self.poscarfile = poscarfile
        self.mol = read(poscarfile)
        self.rCut = rCut
        self.rSurface = rSurface
        surface_neighbors = neighbors(poscarfile, atom=atom, rCut=rSurface, cAtom=cAtom, cAtomIndex=cAtomIndex, rCore=rCut, sort=True)
        self.surface_neighbors = surface_neighbors
        self.n = self.surface_neighbors.get_number_of_neighbors()   # number of surface charges
        self.center_index = self.surface_neighbors.center_index     # center atom index
        if num_sites <= self.n:
            print("The number of potential sites used for fitting must be larger" 
                                 "than the number of charges! We thus use 2 x num of chgs.")
            self.m = 2 * self.n
        else:
            self.m = num_sites              # number of potential sites
        # generate random sites
        self.sites = gen_random_sites(self.poscarfile, num=self.m, deps=0.1, atom=self.center_index)    # 0.1 A is considered as too close
        # get exact potential
        self.exact_pot = get_exact_potential(self.poscarfile, self.sites)
        # get finite potential
        self.finite_pot = get_finite_potential(self.poscarfile, self.sites, rCut=self.rCut, atom=self.center_index)
        self.exact_left_pot = self.exact_pot - self.finite_pot
        self.fitted = False
    
    def _model_build(self):
        """
        Build matrix A and b for linear-squares problem. A: mxn, b: mx1
        """
        self.b = self.exact_left_pot.copy()
        m, n = self.m, self.n
        self.A = np.zeros((m, n), dtype=np.float64)
        fracs = self.mol.get_scaled_positions()
        indices, offsets = self.surface_neighbors.get_neighbors()
        cell = self.mol.get_cell()
        for i in range(m):
            for j in range(n):
                dx_frac = fracs[indices[j]] + offsets[j] - self.sites[i]
                dx_cartesian = np.matmul(dx_frac, cell)
                self.A[i,j] = 1.0e0 / np.linalg.norm(dx_cartesian)
        self.A *= coef_pot
    
    def run_fit(self, sigma_threshold = 1.0e-8):
        """
        Perform the actual charge fitting.
        :param sigma_threshold: threshold for the sigular values of A, below which the singular value is treated as zero.
        """
        self._model_build()
        m, n = self.m, self.n
        x = np.zeros(n, dtype=np.float64)
        u, s, vt = np.linalg.svd(self.A, full_matrices=False, compute_uv=True)
        v = vt.T
        n_sigma = 0
        for i in range(n):
            if s[i] > sigma_threshold:
                n_sigma += 1
                x += np.dot(u[:,i], self.b) / s[i] * v[:,i]
            else:
                break
        self.surf_chgs = x.copy()
        self.n_sigma = n_sigma  # the number of singular values used in linear-squares fitting
        self.fitted = True
    
    def show_res(self):
        """
        Summary of the potential fitting process.
        """
        
        def MAE_potential(charges):
            """
            Calculate the mean absolute error of the electrostaic potential at the sites.
            charges: (n,) 1d array
            """
            resdual = np.matmul(self.A, charges) - self.b
            mae = np.abs(resdual).sum() / self.m
            return mae
        
        print("Number of sites =", self.m)
        print("Number of surface point charges =", self.n)
        if not self.fitted:
            self.run_fit()
        print("Number of sinular values used for fitting =", self.n_sigma)
        raw_chgs = self.surface_neighbors.get_charge_list()
        raw_mae = MAE_potential(raw_chgs)
        mae = MAE_potential(self.surf_chgs)
        print(f"Mean absolute error of electrostatic potential for raw (formal) point charges = {raw_mae:10.5f} V.")
        print(f"Mean absolute error of electrostatic potential for fitted point charges = {mae:10.5f} V.")
    
    # The following 3 functions calculate potentials at given sites, and are used for visualization purposes.
    def fitted_surface_potential_func(self, poscarfile, frac_sites):
        """
        Function to calculate surface potential (i.e. potential generated by surface charges) at some given
        sites (frac_sites).This function is mainly used as argument of potential_surface_c() in surface_plot.py for
        visualization purposes.
        
        The arguments poscarfile and frac_sites is needed by potential_surface_c(), though here poscarfile is obviously
        useless.
        """
        if not self.fitted:
            self.run_fit()
        mol = self.mol
        cell = mol.get_cell()
        fracs = mol.get_scaled_positions()
        indices, offsets = self.surface_neighbors.get_neighbors()
        potential = np.zeros(len(frac_sites), dtype=np.float64)
        for i, site in enumerate(frac_sites):
            i_surf_chg = 0
            for j, offset in zip(indices, offsets):
                displacement = np.matmul(fracs[j] + offset - site, cell)
                d = np.linalg.norm(displacement)
                potential[i] += self.surf_chgs[i_surf_chg] / d
                i_surf_chg += 1
        potential *= coef_pot
        return potential
    
    def fitted_total_potential_func(self, poscarfile, frac_sites):
        """
        Calculate total electrostatic potential at given sites generated by core point charges and
        fitted surface charges.
        """
        core_potential = get_finite_potential(poscarfile=self.poscarfile, frac_sites=frac_sites, rCut=self.rCut, atom=self.center_index)
        surface_potential = self.fitted_surface_potential_func(poscarfile, frac_sites)
        return core_potential + surface_potential
    
    def fitted_left_potential_func(self, poscarfile, frac_sites):
        """
        Calculate the potential difference between the exact total potential and the fitted total potential
        at given sites.
        """
        exact_pot = get_exact_potential(poscarfile=self.poscarfile, frac_sites=frac_sites)
        fitted_pot = self.fitted_total_potential_func(poscarfile=self.poscarfile, frac_sites=frac_sites)
        return exact_pot - fitted_pot