
from math import pi
import numpy as np
from ase.io import read
from matplotlib import pyplot as plt

def potential_surface_c(poscarfile, potential_func, c=0.5e0, savefig=False, figname="pot.png", showfig = True):
    """
    Calculate exact potential on a given surface (constant c value)
    :param poscarFile: name of the POSCAR file
    :param potential_func: a function which takes poscafile and frac_sites as parameters 
                           and return potential array.
    :param c: float, value of c for the a-b plane where the potential is to be calculated.
    """
    x = np.linspace(0.0, 1.0, 31)
    frac_sites = np.zeros((len(x) ** 2, 3))
    frac_sites[:, 2] = c
    index = 0
    for i in range(len(x)):
        for j in range(len(x)):
            frac_sites[index, 0] = x[i]
            frac_sites[index, 1] = x[j]
            index += 1
    potential = potential_func(poscarfile=poscarfile, frac_sites=frac_sites)
    # Next we generate x-y coordinates in the a-O-b plane:
    # vector a has coordinates (1.0, 0.0)
    # vector b has coordinates (b/a * cos\gamma, b/a * sin\gamma)
    mol = read(poscarfile)
    lengths = mol.cell.lengths()
    angles = mol.cell.angles()
    b_len = lengths[1] / lengths[0]
    gamma = angles[2] / 180.0 * pi
    a_coord = np.array([1.0e0, 0.0e0])
    b_coord = np.array([b_len * np.cos(gamma), b_len * np.sin(gamma)])
    data = np.zeros(frac_sites.shape, dtype=np.float64)
    data[:, 2] = potential[:]
    for i in range(len(data)):
        data[i,0:2] = frac_sites[i, 0] * a_coord + frac_sites[i, 1] * b_coord
    # data now is a list of (x, y, V(x,y)) data points. x, y are coordinates in the a-b plane (c value fixed).
    # next plot 3D surface of the electrostatic potential
    shape = (len(x), len(x))
    xx, yy, zz = np.zeros(shape=shape), np.zeros(shape=shape), np.zeros(shape=shape)
    index = 0
    for i in range(len(x)):
        for j in range(len(x)):
            xx[i, j] = data[index, 0]
            yy[i, j] = data[index, 1]
            zz[i, j] = data[index, 2]
            index += 1
    fig = plt.figure()
    ax = plt.axes(projection="3d")
    ax.plot_surface(xx, yy, zz, rstride = 1, cstride = 1, cmap="rainbow")
    ax.contour(xx, yy, zz, offset=zz.min(), cmap="rainbow")
    ax.set_xlabel("X")
    ax.set_ylabel("Y")
    ax.set_zlabel("Potential (V)")
    if savefig:
        plt.savefig(figname, dpi=650)
    if showfig:
        plt.show()

if __name__ == "__main__":
    
    from .exact_potential import get_exact_potential
    from .finite_potential import get_finite_potential
    
    # wrapper of the finite potential generated by charges within a given cutoff
    def finite_potential_func(poscarfile, frac_sites):
        return get_finite_potential(poscarfile, frac_sites, rCut=15.22, atom=0)
    
    # the potential left, which is generated by ions out of a given cutoff
    def left_potential_func(poscarfile, frac_sites):
        pot_exact = get_exact_potential(poscarfile, frac_sites)
        pot_finite = finite_potential_func(poscarfile, frac_sites)
        return pot_exact - pot_finite
    
    filename = "POSCAR.LaF3.vasp"
    #potential_surface_c(filename, get_exact_potential, c=0.5, savefig=True)
    #potential_surface_c(filename, finite_potential_func, c=0.5, savefig=True)
    potential_surface_c(filename, left_potential_func, c=0.5, savefig=True)
